env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - 'svelte3'
  - '@typescript-eslint'
overrides:
  - files: ['*.svelte']
    processor: 'svelte3/svelte3'
settings:
  svelte3/typescript: true
rules:
  quotes:
    - warn
    - "double"
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/ban-ts-comment': off
